import showdown from "showdown";

// format bytes to human readable string
export function formatBytes(bytes, decimals = 2) {
  if (bytes === 0) return "0 Bytes";
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ["Bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + " " + sizes[i];
}

export const getCurrentDate = () => {
  return formatDate(Date.now());
};

export const formatDate = (timestamp) => {
  var now = new Date(timestamp);
  var year = now.getFullYear(); // 年
  var month = now.getMonth() + 1; // 月，需要加1
  month = month < 10 ? "0" + month : month;
  var day = now.getDate(); // 日
  day = day < 10 ? "0" + day : day;
  var hour = now.getHours(); // 时（24小时制）
  hour = hour < 10 ? "0" + hour : hour;
  var minute = now.getMinutes(); // 分
  minute = minute < 10 ? "0" + minute : minute;
  var second = now.getSeconds();
  second = second < 10 ? "0" + second : second;

  // 格式化为 yyyy-MM-dd HH:mm:ss 形式
  return (
    year + "-" + month + "-" + day + " " + hour + ":" + minute + ":" + second
  );
};

export function convertChatToHTML(chat) {
  const converter = new showdown.Converter();
  const markdown = convertChatToMarkdown(chat);
  const html = converter.makeHtml(markdown);
  return `<!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    </head>
    <body>
      <div class="min-h-screen bg-gray-50 py-8 flex flex-col justify-center relative overflow-hidden lg:py-12">
        <img src="/img/beams.jpg" alt="" class="fixed top-48 left-1/2 -translate-x-2/3 -translate-y-1/2 max-w-none" width="1308" />
        <div class="absolute inset-0 bg-[url(/img/grid.svg)] bg-top [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
        <div class="relative w-full px-6 py-12 bg-white shadow-xl shadow-slate-700/10 ring-1 ring-gray-900/5 md:max-w-3xl md:mx-auto lg:max-w-4xl lg:pt-16 lg:pb-28">
          <div class="max-w-prose mx-auto lg:text-lg">
            <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 433.24 107" class="h-6">
              <path d="m6.7,53.5C6.7,27.64,27.75,6.67,53.71,6.67c12.95,0,24.67,5.21,33.18,13.65,1.59-1.37,3.31-2.83,5.13-4.32C82.27,6.13,68.71,0,53.71,0,24.05,0,0,23.95,0,53.5c0,14.46,5.76,27.58,15.12,37.21.75-.9,4.06-5.43,4.06-5.43-7.75-8.35-12.49-19.51-12.49-31.78h0Z" fill="#426cb4" stroke-width="0"/>
              <path d="m100.67,51.13c.04.79.06,1.58.06,2.37,0,25.86-21.05,46.83-47.01,46.83-10.68,0-20.53-3.55-28.43-9.53,2.47-1.71,4.6-3.09,5.76-3.63,5.6-2.62,14.17-4.93,23.05-8.15l-6.65-1.75s23.26-1.91,35.01-11.33l-6.87-1.96C121.5,45.77,112.46,0,112.46,0c-1.53,5.99-14.51,19.52-14.51,19.52l-.09-4.12c-10.77,8.47-19.29,16.8-19.29,16.8l3.36-9.05c-14.94,9.94-28.52,18.84-28.52,18.84l5.83-8.62c-26.05,8.65-37.34,33.82-38.45,51.6,0,0,20.67-26.07,45.01-38.96,0,0-30.12,22.88-55.6,55.86,0,0,4.51-3.45,9.42-7.04,9.27,7.6,21.15,12.16,34.09,12.16,29.67,0,53.71-23.95,53.71-53.5,0-3.34-.31-6.61-.9-9.79-1.66,2.51-3.59,5-5.86,7.41h0Z" fill="#426cb4" stroke-width="0"/>
              <text transform="translate(121.18 77.64)" font-family="PingFangSC-Medium-GBpc-EUC-H, &apos;PingFang SC&apos;" font-size="60" font-weight="500"><tspan x="0" y="0">Ollama</tspan><tspan x="197.28" y="0" fill="#2463eb">One</tspan></text>
            </svg>
          </div>
          <div class="mt-8 prose prose-slate mx-auto lg:prose-lg">${html}<p>Generated by <strong><a href="https://ollama.com/library/${chat.model}" target="_blank">${chat.model}</a></strong>.</p></div>
        </div>
      </div>
    </body>
  </html>`;
}

export function convertChatToMarkdown(chat) {
  return chat.messages.map((message) => message.content).join("\n\n---\n\n");
}
